model:
  node_embed_size: 256
  edge_embed_size: 128
  num_layers: 6
  act_fn: silu
  ln: True
  node_features:
    c_s: ${model.node_embed_size}
    c_bb_input: ${model.bb_embedder.c_node_dim}
    c_bb_emb: 128
    c_timestep_emb: 128
    node_extra_dim: 18
  edge_features:
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    feat_dim: 64
    max_radius: .inf
    max_neighbors: 1000
    trans_n_freqs: 32
    rot_n_freqs: 32
    dist_emb: sin
    rot_dist_emb: sin
    inclination_emb_dim: 32
    represent_angle_edge_to_lattice: true
  bb_embedder:
    c_node_dim: 64
    c_edge_dim: 64
    c_hidden_dim: 64
    max_radius: 6
    max_neighbors: 100
    max_atoms: 17
    num_layers: 6
    num_atom_types: 7
    use_attention_pooling: True